version: '3.8'

services:


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - db


  db:
     image : mysql
     container_name : mysql
     volumes:
       - ./mysql/data:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_DATABASE: laravel
       MYSQL_ROOT_PASSWORD: laravel


  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     ports:
       - "3400:80"
     depends_on:
       - db

